version: "3.8"
services:
  db:
    image: postgres:15
    container_name: invoiceiq-db-frontend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: invoiceiq_frontend
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db_data:
    name: invoiceiq-frontend
