version: '3.8'
services:
  db:
    image: postgres:15
    container_name: invoiceiq-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoiceiq
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
 
volumes:
  db_data:
    name: invoiceiq-data
# networks:
#   invoiceiq_network:
#     name: invoiceiq_network